[Rainmeter]
Update=-1
AccurateText=1
DynamicVariables=1
AntiAlias=1

[Variables]


[Metadata]
Name=Kephalonian Demigod Skin - Compass
Author= ltszatyi
Information=Contact: https://www.deviantart.com/ltszatyi
Version=1.01

;-----------------------------------Compass Background----------------------------------------
[NavigationLineBackground]
Meter=Shape
Shape=Path BackgroundSegment | StrokeWidth 0 | Fill LinearGradient BlackFadeGradient | 
BackgroundSegment= 51,51 | LineTo 320,51 | LineTo 329,55 | LineTo 336,51 | LineTo 606,51 | LineTo 598,61 | LineTo 58,61 | ClosePath 1
BlackFadeGradient= 180 | 0,0,0,0 ; 0.0 | 45,45,45,110 ; 0.5 | 0,0,0,0 ; 1.0 |

;-----------------------------------Compass Element Line Top-----------------------------------
[NavigationLine1]
Meter=Shape
X=1
Y=1
Shape=Path UpperSegment | StrokeWidth 2,5 | Stroke LinearGradient WhiteFadeStrokeGradient | StrokeStartCap Triangle | StrokeEndCap Triangle
UpperSegment= 50,50 | LineTo 320,50 | LineTo 328,55 | LineTo 336,50 | LineTo 606,50 | ClosePath | 
WhiteFadeStrokeGradient= 180 | 255,255,255,30 ; 0.0 | 255,255,255,255 ; 0.5 | 255,255,255,30 ; 1.0 |

;-----------------------------------Compass Element Line Middle-----------------------------------
[NavigationLine2]
Meter=Shape
X=1
Y=1
Shape=Path LowerSegment | StrokeWidth 1 | Stroke LinearGradient WhiteFadeStrokeGradient | StrokeStartCap Triangle | StrokeEndCap Triangle
LowerSegment=54,55 | LineTo 602,55 | ClosePath |
WhiteFadeStrokeGradient= 180 | 255,255,255,30 ; 0.0 | 255,255,255,255 ; 0.5 | 255,255,255,30 ; 1.0 |

;-----------------------------------Compass Element Sanctuary-----------------------------------
[Icon1]
Meter=Image
Imagename=#ROOTCONFIGPATH#@Resources\Icons\sanctuary.png
X=380
Y=42
W=22
AntiAlias=1
ImageTint=245,245,245,165
ClickThrough=1

;-----------------------------------Compass Element Treasure-----------------------------------
[Icon2]
Meter=Image
Imagename=#ROOTCONFIGPATH#@Resources\Icons\treasure.png
X=80
Y=42
W=24
AntiAlias=1
ImageTint=245,245,245,100
ClickThrough=1
;-----------------------------------Compass Element ?-----------------------------------
[Icon3]
Meter=String
Text=?
X=180
Y=38
FontSize=22
FontFace=Roboto
FontWeight=500
FontColor=255,255,255,245
StringEffect=Border
FontEffectColor=0,0,0,185
AntiAlias=1
MouseOverAction=[!ShowMeter MeterQ][!Redraw]
MouseLeaveAction=[!HideMeter MeterQ][!Redraw]
;-----------------------------------?-----------------------------------
[MeterQ]
Meter=String
Text=Perhaps the goat is there with Cyclopse's eye...
StringAlign=Center
X=(#SCREENAREAWIDTH#/5)
Y=925
FontSize=16
FontFace=Roboto
FontWeight=500
FontColor=255,255,255,245
StringEffect=Border
FontEffectColor=0,0,0,220
AntiAlias=1
Hidden=1