[Rainmeter]
Update=330

[Metadata]
Name=Kephalonian Demigod Skin - Bounty RAM Meter
Author= ltszatyi
Information=Contact: https://www.deviantart.com/ltszatyi
Version=1.01

[Variables]
NeutralGray=89, 108, 118, 230
RedBar=90 | 255,0,0,255; 0.0 | 141,0,0,255; 1.0 |
GrayIcon=159,159,159,255
HoverRed=255,69,67,255
BarBGray=88,109,117,255

;-----------------------------------Footer Dock as Launch tray-----------------------------------
[IconBarBG]
DynamicVariables=1
Meter=Shape
Shape=Rectangle 0,0,312,14 | Fill Color 52, 68, 74, 255 | StrokeWidth 1 | StrokeColor #GrayIcon#
X=9
Y=19
;-----------------------------------Calculations for RAM usage-----------------------------------
[MeasurePhysMemTotal]
Measure=PhysicalMemory
Total=1

[MeasurePhysMemFree]
Measure=PhysicalMemory
InvertMeasure=1

[MeasureUsedPercent]
Measure=Calc
Formula=(MeasurePhysMemUsed / MeasurePhysMemTotal) * 100
;-----------------------------------Progress Bar-----------------------------------
[MeterUsedMemoryBar]
MeasureName=MeasurePhysMemUsed
Meter=BAR
X=11
Y=21
W=300
H=14
SolidColor=#BarBGray#
BarImage=#ROOTCONFIGPATH#@Resources\Bar\bounty-bar.jpg
BarOrientation=Horizontal
;-----------------------------------Conditions for bounty level 1-----------------------------------
[MeasurePhysMemUsed]
Measure=PhysicalMemory
UpdateDivider=2
IfCondition=MeasureUsedPercent >= 20
IfTrueAction=[!SetOption MeterPercentHelmet20%Color ImageTint #HoverRed#][!Redraw]
IfFalseAction=[!SetOption MeterPercentHelmet20%Color ImageTint #GrayIcon#][!Redraw]
OnUpdateAction=[!UpdateMeter MeterPercentHelmet20%Color][!Redraw]
;-----------------------------------Conditions for bounty level 2-----------------------------------
[MeasurePhysMemUsed2]
Measure=PhysicalMemory
UpdateDivider=2
IfCondition=MeasureUsedPercent >= 40
IfTrueAction=[!SetOption MeterPercentHelmet40%Color ImageTint #HoverRed#][!Redraw]
IfFalseAction=[!SetOption MeterPercentHelmet40%Color ImageTint #GrayIcon#][!Redraw]
OnUpdateAction=[!UpdateMeter MeterPercentHelmet40%Color][!Redraw]
;-----------------------------------Conditions for bounty level 3-----------------------------------
[MeasurePhysMemUsed3]
Measure=PhysicalMemory
UpdateDivider=2
IfCondition=MeasureUsedPercent >= 60
IfTrueAction=[!SetOption MeterPercentHelmet60%Color ImageTint #HoverRed#][!Redraw]
IfFalseAction=[!SetOption MeterPercentHelmet60%Color ImageTint #GrayIcon#][!Redraw]
OnUpdateAction=[!UpdateMeter MeterPercentHelmet60%Color][!Redraw]
;-----------------------------------Conditions for bounty level 4-----------------------------------
[MeasurePhysMemUsed4]
Measure=PhysicalMemory
UpdateDivider=2
IfCondition=MeasureUsedPercent >= 80
IfTrueAction=[!SetOption MeterPercentHelmet80%Color ImageTint #HoverRed#][!Redraw]
IfFalseAction=[!SetOption MeterPercentHelmet80%Color ImageTint #GrayIcon#][!Redraw]
OnUpdateAction=[!UpdateMeter MeterPercentHelmet80%Color][!Redraw]
;-----------------------------------Conditions for bounty level 5-----------------------------------
[MeasurePhysMemUsed5]
Measure=PhysicalMemory
UpdateDivider=2
IfCondition=MeasureUsedPercent >= 95
IfTrueAction=[!SetOption MeterPercentHelmet100%Color ImageTint #HoverRed#][!Redraw]
IfFalseAction=[!SetOption MeterPercentHelmet100%Color ImageTint #GrayIcon#][!Redraw]
OnUpdateAction=[!UpdateMeter MeterPercentHelmet100%Color][!Redraw]
;-----------------------------------Outline for bounty level helmet1-----------------------------------
[MeterPercentHelmet20%Black]
Meter=Image
ImageName=#ROOTCONFIGPATH#@Resources\Icons\helmet-outline.png
W=32
X=65
Y=8
ImageTint=0,0,0,255
;-----------------------------------Bounty level helmet1-----------------------------------
[MeterPercentHelmet20%Color]
Meter=Image
ImageName=#ROOTCONFIGPATH#@Resources\Icons\helmet.png
W=32
X=65
Y=[MeterPercentHelmet20%Black:Y]
ImageTint=#GrayIcon#
;-----------------------------------Outline for bounty level helmet2-----------------------------------
[MeterPercentHelmet40%Black]
Meter=Image
ImageName=#ROOTCONFIGPATH#@Resources\Icons\helmet-outline.png
W=32
X=126
Y=[MeterPercentHelmet20%Black:Y]
ImageTint=0,0,0,255
;-----------------------------------Bounty level helmet2-----------------------------------
[MeterPercentHelmet40%Color]
Meter=Image
ImageName=#ROOTCONFIGPATH#@Resources\Icons\helmet.png
W=32
X=126
Y=[MeterPercentHelmet20%Black:Y]
ImageTint=#GrayIcon#
;-----------------------------------Outline for bounty level helmet3-----------------------------------
[MeterPercentHelmet60%Black]
Meter=Image
ImageName=#ROOTCONFIGPATH#@Resources\Icons\helmet-outline.png
W=32
X=186
Y=[MeterPercentHelmet20%Black:Y]
ImageTint=0,0,0,255
;-----------------------------------Bounty level helmet3-----------------------------------
[MeterPercentHelmet60%Color]
Meter=Image
ImageName=#ROOTCONFIGPATH#@Resources\Icons\helmet.png
W=32
X=186
Y=[MeterPercentHelmet20%Black:Y]
ImageTint=#GrayIcon#
;-----------------------------------Outline for bounty level helmet4-----------------------------------
[MeterPercentHelmet80%Black]
Meter=Image
ImageName=#ROOTCONFIGPATH#@Resources\Icons\helmet-outline.png
W=32
X=245
Y=[MeterPercentHelmet20%Black:Y]
ImageTint=0,0,0,255
;-----------------------------------Bounty level helme4-----------------------------------
[MeterPercentHelmet80%Color]
Meter=Image
ImageName=#ROOTCONFIGPATH#@Resources\Icons\helmet.png
W=[MeterPercentHelmet80%Black:W]
X=[MeterPercentHelmet80%Black:X]
Y=[MeterPercentHelmet80%Black:Y]
ImageTint=#GrayIcon#
;-----------------------------------Outline for bounty level helmet5-----------------------------------
[MeterPercentHelmet100%Black]
Meter=Image
ImageName=#ROOTCONFIGPATH#@Resources\Icons\helmet-outline.png
W=32
X=300
Y=[MeterPercentHelmet20%Black:Y]
ImageTint=0,0,0,255
;-----------------------------------Bounty level helmet5-----------------------------------
[MeterPercentHelmet100%Color]
Meter=Image
ImageName=#ROOTCONFIGPATH#@Resources\Icons\helmet.png
W=[MeterPercentHelmet100%Black:W]
X=[MeterPercentHelmet100%Black:X]
Y=[MeterPercentHelmet20%Black:Y]
ImageTint=#GrayIcon#









