[Rainmeter]
Update=3000
AccurateText=1
DynamicVariables=1
AntiAlias=1

[Metadata]
Name=Kephalonian Demigod Skin - Level CPU
Author= ltszatyi
Information=Contact: https://www.deviantart.com/ltszatyi
Version=1.01
;-----------------------------------Level Badge Frame-----------------------------------
[Frame]
Meter=Shape
Shape=Path ShieldFrame | StrokeWidth 2 | Stroke Color 255,255,255,255 | Fill Color 79, 95, 107, 255 | SetRoundJoin 1 | Scale 0.8, 0.8 |
ShieldFrame= 02,09, | LineTo 24,5 | LineTo 46,09 | LineTo 46,45 | LineTo 24,61 | LineTo 02,45 | ClosePath 1

;-----------------------------------MeasureAverageCPU-----------------------------------
[MeasureCPU]
Measure=CPU
Processor=0

;-----------------------------------Calculating level min 10 max 99 -----------------------------------
[Measure100]
Measure=Calc
Formula=100-MeasureCPU
MaxValue=99
MinValue=10
DynamicVariables=1

;-----------------------------------Level number-----------------------------------
[Level]
Meter=String
AntiAlias=1
MeasureName=Measure100
MaxValue=99
DynamicVariables=1
X=12
Y=17
FontSize=16
FontFace=Roboto
FontWeight=500
FontColor=255,255,255,255
NumOfDecimals=0
Text="%1"
