[Rainmeter]
Update=-1
AccurateText=1
DynamicVariables=1
AntiAlias=1

[Variables]
AbilityBrown=50,46,28,255
GradientC1=255,255,171,255
GradientC2=202,196,116,255

[Metadata]
Name=Kephalonian Demigod Skin - Abilities - Launch Bar
Author= ltszatyi
Information=Contact: https://www.deviantart.com/ltszatyi
Version=1.01

;--------------------- Base Section -------------------------
[RangedBarIcon1]
Meter=Shape
Shape=Ellipse 40,30,25,25 | Fill LinearGradient ButtonGradient | StrokeWidth 2 | StrokeColor 245, 237, 179,255 |
ButtonGradient=90 | #GradientC1# ; 0.0 | #GradientC2# ; 1.0 |
[RangedBarIcon2]
Meter=Shape
Shape=Ellipse 110,30,25,25 | Fill LinearGradient ButtonGradient | StrokeWidth 2 | StrokeColor 245, 237, 179,255 |
ButtonGradient=90 | #GradientC1# ; 0.0 | #GradientC2# ; 1.0 |
[RangedBarIcon3]
Meter=Shape
Shape=Ellipse 180,30,25,25 | Fill LinearGradient ButtonGradient | StrokeWidth 2 | StrokeColor 245, 237, 179,255 |
ButtonGradient=90 | #GradientC1# ; 0.0 | #GradientC2# ; 1.0 |
[RangedBarIcon4]
Meter=Shape
Shape=Ellipse 250,30,25,25 | Fill LinearGradient ButtonGradient | StrokeWidth 2 | StrokeColor 245, 237, 179,255 |
ButtonGradient=90 | #GradientC1# ; 0.0 | #GradientC2# ; 1.0 |
[MeleeBarIcon1]
Meter=Shape
Shape=Ellipse 80,110,40,40 | Fill LinearGradient ButtonGradient | StrokeWidth 2 | StrokeColor 245, 237, 179,255 |
ButtonGradient=90 | #GradientC1# ; 0.0 | #GradientC2# ; 1.0 |
[MeleeBarIcon2]
Meter=Shape
Shape=Ellipse 180,110,40,40 | Fill LinearGradient ButtonGradient | StrokeWidth 2 | StrokeColor 245, 237, 179,255 |
ButtonGradient=90 | #GradientC1# ; 0.0 | #GradientC2# ; 1.0 |
[MeleeBarIcon3]
Meter=Shape
Shape=Ellipse 280,110,40,40 | Fill LinearGradient ButtonGradient | StrokeWidth 2 | StrokeColor 245, 237, 179,255 |
ButtonGradient=90 | #GradientC1# ; 0.0 | #GradientC2# ; 1.0 |
[MeleeBarIcon4]
Meter=Shape
Shape=Ellipse 380,110,40,40 | Fill LinearGradient ButtonGradient | StrokeWidth 2 | StrokeColor 245, 237, 179,255 |
ButtonGradient=90 | #GradientC1# ; 0.0 | #GradientC2# ; 1.0 |
;------------------------ Icons Section -------------------------------------
;------------------------ Computer / MyPC / Documents ------------------------ 
[MeleeIcon1]
Meter=Image
ImageName=#ROOTCONFIGPATH#@Resources\Icons\file-paper-2-line.png
W=46
X=56
Y=86
ImageTint=#AbilityBrown#
LeftMouseDownAction=[Shell:::{20D04FE0-3AEA-1069-A2D8-08002B30309D}]
MouseOverAction=[!ShowMeter Melee1Text][!Redraw]
MouseLeaveAction=[!HideMeter Melee1Text][!Redraw]
[Melee1Text]
Meter=String
Text="Let's see what we have here!"
FontFace=Roboto
FontSize=16
FontWeight=500
FontColor=255,255,255,245
StringAlign=Center
StringEffect=Border
FontEffectColor=0,0,0,185
AntiAlias=1
X=(#SCREENAREAWIDTH#/2)
;750
Y=80
Hidden=1
;------------------------ Browser (default) ------------------------ 
[MeleeIcon2]
Meter=Image
ImageName=#ROOTCONFIGPATH#@Resources\Icons\earth-fill.png
W=56
X=152
Y=83
ImageTint=#AbilityBrown#
LeftMouseDownAction=["C:\Program Files\Google\Chrome\Application\chrome.exe" --profile-directory="Default"]
MouseOverAction=[!ShowMeter Melee2Text][!Redraw]
MouseLeaveAction=[!HideMeter Melee2Text][!Redraw]
[Melee2Text]
Meter=String
Text="I should try to stay out of sight."
FontFace=Roboto
FontSize=16
FontFace=Roboto
FontWeight=500
FontColor=255,255,255,245
StringEffect=Border
StringAlign=Center
FontEffectColor=0,0,0,185
AntiAlias=1
X=(#SCREENAREAWIDTH#/2)
;750
Y=80
Hidden=1
;------------------------ Calendar (Google) ------------------------ 
[MeleeIcon3]
Meter=Image
ImageName=#ROOTCONFIGPATH#@Resources\Icons\calendar-todo-fill.png
W=48
X=256
Y=88
ImageTint=#AbilityBrown#
LeftMouseDownAction=["https://calendar.google.com/calendar"]
MouseOverAction=[!ShowMeter Melee3Text][!Redraw]
MouseLeaveAction=[!HideMeter Melee3Text][!Redraw]
[Melee3Text]
Meter=String
Text="All in a days work."
FontFace=Roboto
FontSize=16
FontFace=Roboto
FontWeight=500
FontColor=255,255,255,245
StringEffect=Border
StringAlign=Center
FontEffectColor=0,0,0,185
AntiAlias=1
X=(#SCREENAREAWIDTH#/2)
;750
Y=80
Hidden=1
;------------------------ E-mails (Outlook/Google) ------------------------ 
[MeleeIcon4]
Meter=Image
ImageName=#ROOTCONFIGPATH#@Resources\Icons\quill-pen-fill.png
W=48
X=358
Y=86
ImageTint=#AbilityBrown#
;LeftMouseDownAction=["C:\Program Files\Microsoft Office\root\Office16\OUTLOOK.EXE"]
LeftMouseDownAction=["https://mail.google.com/mail/"]
MouseOverAction=[!ShowMeter Melee4Text][!Redraw]
MouseLeaveAction=[!HideMeter Melee4Text][!Redraw]
[Melee4Text]
Meter=String
Text="I got your message on the board. What's going on?"
;"Again, Mal[\x00E1]ka?!"
FontSize=16
FontFace=Roboto
FontWeight=500
FontColor=255,255,255,245
StringEffect=Border
StringAlign=Center
FontEffectColor=0,0,0,185
AntiAlias=1
X=(#SCREENAREAWIDTH#/2)
;750
Y=80
Hidden=1
; ------------------------ Settings / Control Panel ------------------------ 
[RangedIcon1]
Meter=Image
ImageName=#ROOTCONFIGPATH#@Resources\Icons\hammer-fill.png
W=28
X=26
Y=16
ImageTint=#AbilityBrown#
LeftMouseDownAction=Control Panel
MouseOverAction=[!ShowMeter RangedIcon1Text][!Redraw]
MouseLeaveAction=[!HideMeter RangedIcon1Text][!Redraw]
[RangedIcon1Text]
Meter=String
Text=Salvage nearby Commander!
FontFace=Roboto
FontSize=16
FontWeight=500
FontColor=255,255,255,245
StringEffect=Border
StringAlign=Center
FontEffectColor=0,0,0,185
AntiAlias=1
X=(#SCREENAREAWIDTH#/2)
;750
Y=80
Hidden=1
; ------------------------ Spotify ------------------------ 
[RangedIcon2]
Meter=Image
ImageName=#ROOTCONFIGPATH#@Resources\Icons\music-2-fill.png
W=30
X=95
Y=16
ImageTint=#AbilityBrown#
LeftMouseDownAction=["C:\Program Files\Spotify\Spotify.exe"]
MouseOverAction=[!ShowMeter RangedIcon2Text][!Redraw]
MouseLeaveAction=[!HideMeter RangedIcon2Text][!Redraw]
[RangedIcon2Text]
Meter=String
Text=It's not sea trouble without a song!
FontFace=Roboto
FontSize=16
FontWeight=500
FontColor=255,255,255,245
StringEffect=Border
StringAlign=Center
FontEffectColor=0,0,0,185
AntiAlias=1
X=(#SCREENAREAWIDTH#/2)
;750
Y=80
Hidden=1
;------------------------ Steam ------------------------ 
[RangedIcon3]
Meter=Image
ImageName=#ROOTCONFIGPATH#@Resources\Icons\sword-fill.png
W=30
X=165
Y=17
ImageTint=#AbilityBrown#
LeftMouseDownAction=["C:\Program Files (x86)\Steam\steam.exe"]
MouseOverAction=[!ShowMeter RangedIcon3Text][!Redraw]
MouseLeaveAction=[!HideMeter RangedIcon3Text][!Redraw]
[RangedIcon3Text]
Meter=String
Text="For Sparta!"
FontSize=16
FontFace=Roboto
FontWeight=500
StringAlign=Center
FontColor=255,255,255,245
StringEffect=Border
FontEffectColor=0,0,0,185
AntiAlias=1
X=(#SCREENAREAWIDTH#/2)
;750
Y=80
Hidden=1
;------------------------ Discord ------------------------ 
[RangedIcon4]
Meter=Image
ImageName=#ROOTCONFIGPATH#@Resources\Icons\user-voice-fill.png
W=26
X=237
Y=18
ImageTint=#AbilityBrown#
LeftMouseDownAction=["C:\Program Files (x86)\Discord\discord.exe"]
MouseOverAction=[!ShowMeter RangedIcon4Text][!Redraw]
MouseLeaveAction=[!HideMeter RangedIcon4Text][!Redraw]
[RangedIcon4Text]
Meter=String
Text="Again, Mal[\x00E1]ka?!"
FontSize=16
FontFace=Roboto
FontWeight=500
FontColor=255,255,255,245
StringEffect=Border
StringAlign=Center
FontEffectColor=0,0,0,185
AntiAlias=1
X=(#SCREENAREAWIDTH#/2)
;750
Y=80
Hidden=1