[Rainmeter]
Update=-1

[Metadata]
Name=Kephalonian Demigod Skin - Header
Author= ltszatyi
Information=Contact: https://www.deviantart.com/ltszatyi
Version=1.01
;-----------------------------------Greetings Misthios-----------------------------------
[WelcomeMisthios]
Meter=String
Text="Chaire Misthios!" 
;[\x00E9] - letter "é" in case of need.
X=5
Y=5
FontSize=16
FontFace=Roboto
FontWeight=500
AntiAlias=1
FontColor=255,255,255,245
StringEffect=Border
FontEffectColor=0,0,0,220;
